- route:
    id: routefromyaml
    description: test data producer    
    from:
      uri: 'timer://foo21?period=5000'
      steps:
        - setBody:
            constant: 'Test route from yaml config'
        - log: 'Body ${body}'        